name: Discord Simple Notification

on: 
  push:
    branches: [main]

jobs:
  discord_simple:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Discord with curl
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "ğŸš€ Novo commit em '"${{ github.repository }}"' por '"${{ github.actor }}"'\nğŸ“ '"${{ github.event.head_commit.message }}"'"}' \
          ${{ secrets.SECRETDISCORD }}